[build]
  # Perintah ini memastikan dependensi (node-fetch) terinstal
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  # Arahkan semua request dari /api/* ke fungsi proxy
  from = "/api/*"
  to = "/.netlify/functions/proxy?path=:splat"
  status = 200
